CREATE TABLE controle
(
	id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	nome VARCHAR(50) NOT NULL,
	dono VARCHAR(90) NOT NULL,
	valor VARCHAR(20) NOT NULL,
        atualizacao VARCHAR(20) NOT NULL,
        pedido VARCHAR (20) NOT NULL

);